### PR TITLE
Cb 127 revise nextflow schema file to include added params remove unused ones

### PR DESCRIPTION
**Pull request by lzholl**
## What type of PR is this? (check all applicable)

- [x] 🐛 Bug Fix
- [x] 📝 Documentation Update (within code)

## Description

Merging into the branch Taylor currently has open instead of `dev` since I started my branch off some of his changes. I only changed the nextflow.config and schema files though...

Fixed the metaT nextflow schema file to include all of our parameters so it stops yelling at us:

Screenshot 2023-05-30 at 5 06 25 PM

I also added descriptions for each of the parameters, which is why documentation update is marked. 

## Jira Task

[Link to Jira task.](https://arkeabio.atlassian.net/browse/CB-127)

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📕 notebook(s)
- [x] 🙅 no documentation needed

## Code Quality
- [x] 🎯 The code is properly formatted and adheres to the project's style guide
- [x] 🎯 The code runs without any errors or exceptions

## Testing

You can test that these warnings no longer appear by running `nextflow run main.nf -profile docker --input localdata/smallsheet.csv`

### CODE REVIEW

**Comment by lzholl** [comment]
I did my best. The problem is that my best isn't very good. 😅

**Review by tfalkarkea — APPROVED** [review]
Ran and it looks better, fewer warnings from Nextflow.

Did you intend to remove the subset reads from `localdata/`? That folder is mostly moved onto Google drive for now, and will probably just have some minimal test data in the future, but not sure if this was an intentional change or not.

**Comment by lzholl** [comment]
I think that's because I compressed those files. They're still there though.

**Pull request merged**
