### PR TITLE
Cb 51 factor existing modules into this new pipeline

### PR DESCRIPTION
**Pull request by tfalkarkea**
Finishing this Jira task in order to re-do it as smaller modules.

In the mean time, this modified pipeline can successfully run the sample data from start to finish. A litany of modules and subworkflows have been removed, and I have tried to simplify some of the modules. See commit titles for more details.

I also began a bowtie2 workflow, which should be able to build and align and remove reads matching _B. taurus_. This will get spun off into its own Jira task soon enough.

Clone the repo and try running the pipeline with `nextflow run main.nf -profile test,docker --outdir outdir/`.

### CODE REVIEW

**Review by lzholl — COMMENTED** [review]
I'm getting an error when I try to run it locally.

`Unable to read script: '/Users/lauraholland/github/metatdenovo/./workflows/../subworkflows/local/diginorm.nf' -- cause: Can't find a matching module file for include: ../../modules/local/khmer/normalizebymedian`

The khmer folder seems to be missing?

Update: wasn't on the correct branch of course, then Docker was giving me issues. Updated Docker and adjusted resources and now it's running.

**Comment by lzholl** [comment]
I was able to get the pipeline running but it kept getting hung up in different spots. Might be a bug related to compatibility with the M1 chip. Something to sort out in the future. Otherwise, the code itself and changes made look good.

**Review by lzholl — APPROVED** [review]

**Comment by tfalkarkea** [comment]
@laurenfitch if you choose to run this, include `arm` as a `-profile` option (comma separated). Otherwise, FastQC will hang.

**Review by lzholl — APPROVED** [review]
Retry of approval?

**Comment by laurenfitch** [comment]
@tfalkarkea , can you please give write access on this repo to the GitHub team Bioinformatics? Then Laura will have write access and this approval should become mergeable.

**Comment by tfalkarkea** [comment]
@laurenfitch Thanks for the heads up! We were scratching our heads about it not going through. Strange that forking the repo into the org isn't enough to create write permissions.

**Comment by laurenfitch** [comment]
> @laurenfitch Thanks for the heads up! We were scratching our heads about it not going through. Strange that forking the repo into the org isn't enough to create write permissions.

I think the default right now is that only the repo owner (i.e. the person who created it) has write access. It looks like the org owner (Andrea) can [change the default](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/setting-base-permissions-for-an-organization#setting-base-permissions), so I'll ask her to do that.

**Pull request merged**
