### PR TITLE
Cb 243 ensure kraken 2 is saving filtered non archaeal reads

### PR DESCRIPTION
**Pull request by tfalkarkea**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [x] 🐛 Bug Fix

## Description

Made a couple small changes, but mostly ensuring that outputs for the bacterial filtering were saved. These can be found in: `arn:aws:s3:::arkeabio-nextflow-general/meta-t_outputs/kraken_bact_out/`  (bad dir because I forgot to make an output dir oops).

Task

[CB-243](https://arkeabio.atlassian.net/browse/CB-243) Ensure Kraken2 is saving filtered non-archaeal reads

## Added tests?

- [x] 🙅 no, because they aren't needed

## Added to documentation?

- [x] 🙅 no documentation needed

## Code Quality
- [x] 🎯 The code is properly formatted and adheres to the project's style guide
- [x] 🎯 The code runs without any errors or exceptions

## Compute Environment

Can run wherever.

## Testing

Tower run can be found [here](https://tower.nf/orgs/ArkeaBio/workspaces/Computational_Biology/watch/gGC5xiNOlc4h8)

### CODE REVIEW

**Review by lzholl — COMMENTED** [review]
ok, this is taking me a minute because the structure of the outputs is confusing to me. From what I can tell, these are all outputs from the same run. Is that right? Except for the old execution trace... 

Screenshot 2023-09-18 at 12 19 52 PM

**Comment by tfalkarkea** [comment]
Yeah I messed up and didn't include an actual named run folder, so it all went in the parent folder (bad). A lot of these commits are trying to fix this sort of problem but it doesn't really work effectively so I scrapped. The actual outputs should be in `kraken_bact_out`

**Comment by tfalkarkea** [comment]
Please don't make me rerun to put it in the right folder

**Comment by lzholl** [comment]
Well the classified bacterial reads are where they should be:

Screenshot 2023-09-18 at 12 30 41 PM

But I guess my concern is down the line we might get confused as to what's an intermediate vs. final output. I get that they all went to the parent folder, but it's still five separate folders to go through, ya know? I'm not gonna make you rerun though since it's a separate issue.

**Review by lzholl — APPROVED** [review]

**Comment by tfalkarkea** [comment]
My beautiful son the pipeline has completed another run:
https://tower.nf/orgs/ArkeaBio/workspaces/Computational_Biology/watch/20lmN0J446kU9z

This is the output structure. There is only one sample for this file, sub1M_SRR18336216, so only one sample folder is listed.
Screenshot 2023-09-19 at 3 13 19 PM

**Pull request merged**
